export const womensNames = [
  'Susan Sarandon',
  'Maya Angelou',
  'Frida Kahlo',
  'Betty Friedan',
  'Gloria Steinem',
  'Alexandria Ocasio-Cortez',
  'Ruth Bader Ginsberg',
  'Simone de Beauvoir',
  'Serena Williams',
  'Indra Nooyi',
  'Anita Hill',
  'Dr Christine Blasey Ford',
  'Angela Merkel',
  'Madonna',
  'Julie Delpy',
  'Malala Yousafzai',
  'Michelle Obama',
  'Sandra Oh',
  'Agnès Varda', 
  'Sheryl Sandberg',
  'Hillary Clinton', 
  'Oprah Winfrey'
];